"""
Explanation generator (Task 6.1 / Story 6.1).

Composes a short "why this fits you" explanation for a Next Cart
recommendation. Every fact used here comes from one of three already-
structured sources: the gap (Epic 4), the candidate's static rationale
(Epic 5's recommendation table), and the user's own profile fields.
Nothing is invented or generated by an LLM — this is plain string
templating over known data, per the roadmap's explicit anti-hallucination
rule for recommendation logic.
"""

from typing import Union

from backend.app.models.profile import Goal, DietaryPattern, ProfileCreate, Profile
from backend.app.models.snapshot import Gap

ProfileLike = Union[Profile, ProfileCreate]

GOAL_PHRASES = {
    Goal.LOSE_WEIGHT: "you're focused on losing weight",
    Goal.GAIN_MUSCLE: "you're focused on building muscle",
    Goal.EAT_HEALTHIER: "you want to eat healthier",
    Goal.MORE_ENERGY: "you're aiming for more energy",
    Goal.MAINTAIN_WEIGHT: "you want to maintain your current weight",
}

_GAP_VERB = {"low": "low in", "high": "high in"}


def generate_explanation(gap: Gap, candidate: dict, profile: ProfileLike) -> str:
    """
    Build a 2-3 sentence, profile-aware explanation.

    `candidate` is one row from data/recommendations.json (must have
    `item`, `action_type`, `rationale`). Short enough to read in seconds
    (Story 6.1); references the specific gap and the user's own goal and
    diet, never a generic claim.
    """

    goal_phrase = GOAL_PHRASES.get(profile.goal, "your goals")
    gap_verb = _GAP_VERB.get(gap.status.value, gap.status.value)

    sentences = [
        f"Because {goal_phrase} and your basket is currently {gap_verb} "
        f"{gap.dimension}, we suggest you {candidate['action_type']} "
        f"{candidate['item']}.",
        candidate["rationale"],
    ]

    if profile.dietary_pattern != DietaryPattern.OMNIVORE:
        sentences.append(
            f"This fits your {profile.dietary_pattern.value} diet — nothing "
            "here conflicts with it."
        )

    return " ".join(sentences)
