"""
Explanation generator (Task 6.1 / Story 6.1).

Composes a short "why this fits you" explanation for a Next Cart
recommendation. Every fact used here comes from one of three already-
structured sources: the gap (Epic 4), the candidate's static rationale
(Epic 5's recommendation table), and the user's own profile fields.
Nothing is invented or generated by an LLM — this is plain string
templating over known data, per the roadmap's explicit anti-hallucination
rule for recommendation logic.
"""

from typing import Union

from backend.app.models.profile import DietaryPattern, ProfileCreate, Profile
from backend.app.models.snapshot import Gap
from backend.app.services import i18n

ProfileLike = Union[Profile, ProfileCreate]


def generate_explanation(gap: Gap, candidate: dict, profile: ProfileLike, lang: str = "en") -> str:
    """
    Build a 2-3 sentence, profile-aware explanation (localized, E13).

    `candidate` is one row from data/recommendations.json (must have
    `item`, `action_type`, `rationale`). Short enough to read in seconds
    (Story 6.1); references the specific gap and the user's own goal and
    diet, never a generic claim.
    """

    goal_key = f"expl.goal.{getattr(profile.goal, 'value', profile.goal)}"
    goal_phrase = i18n.t(lang, goal_key)
    if goal_phrase == goal_key:  # no phrase for this goal → neutral fallback
        goal_phrase = "you want to eat well" if i18n._norm(lang) == "en" else "du dich gut ernähren möchtest"
    gap_verb = i18n.t(lang, f"expl.gap_verb.{gap.status.value}")

    sentences = [
        i18n.t(
            lang, "expl.sentence",
            goal_phrase=goal_phrase,
            gap_verb=gap_verb,
            nutrient=i18n.nutrient(lang, gap.dimension),
            action=candidate["action_type"],
            item=candidate["item"],
        ),
        i18n.rationale_for(candidate, lang),
    ]

    if profile.dietary_pattern != DietaryPattern.NO_SPECIFIC_DIET:
        sentences.append(i18n.t(lang, "expl.diet_fit", diet=profile.dietary_pattern.value))

    return " ".join(sentences)
